### PR TITLE
Dev/2.0

### PR DESCRIPTION
**Pull request by facelessuser**
- Adds multiple copy/paste.
- Copies persist across sessions.
- Add paste selective which allows pasting selective entries from the clipboard.
- Move context menu items to the tab menus as that is the more appropriate place for them.
- Various bug fixes.

### CODE REVIEW

**Comment by rchl** [comment]
@facelessuser could we get this rolling? Do you remember what is left to do. I'd love to maybe contribute some improvements but this should be probably moved out of the way first.

**Comment by facelessuser** [comment]
Yeah, there are some bugs with remembering states across windows and such. This mainly was introduced with the copying multiple files and such. There are some issues if you have the panel open in one view, and then open the panel in another view, things can get messed up IIRC.

It is one of the plugins I have that I hear very little activity on, so it's been a little bit on the back burner. I need to restructure some things to better handle the states from getting off. I think that was the main issue. I'm just often pulled in a number of directions, and when I don't hear very much from a certain plugin, I assume most people are happy with it.

I just need to carve out some time and shake out the remaining issues.

**Comment by rchl** [comment]
I wonder if this plugin got too complex for its own good...
I love it for the functionality that it provides when it comes to just quickly opening files relative to the current file.
I personally never used the copying functionality and would be a bit scared to used to be honest.
Also the name of the plugin doesn't really seem to suggest that it has the file manager like functionality so I'm not sure how many people really expect that to be built in.

But I'm rambling now. The features are not gonna be removed now (unless maybe in a separate "light" version ;)).

**Comment by facelessuser** [comment]
I do use the deletion and copy/paste functionality sometimes. I've never had a real issue with that. With that said, I put a lot into the dev branch, and it's holding up some of the changes because I haven't gotten around to fixing the more experimental stuff. I can probably look to pull how the stable stuff into a new branch to get a new version out the door.

**Comment by facelessuser** [comment]
@rchl https://github.com/facelessuser/FuzzyFileNav/pull/38 will pull in all the stable fixes and changes leaving behind the unstable stuff. This should be very easy to get polished up and maybe even released sometime this week. This will allow us to make new changes to a stable branch and allow me to tinker with unstable changes seperately.

**Comment by facelessuser** [comment]
Closing this issue in favor of #38. We will revisit multi copy/paste again in the future. Before releasing #38, we'll see if there were any copy/paste fixes we should pick up, but I believe all other changes of relevance are in #38.

**Pull request closed without merging**
