### PR TITLE
add missing . to fix markdown ordered list

### PR DESCRIPTION
**Pull request by dsernst**
Very minor change to fix the formatting of the ordered list. See here for where the list was not properly indented: http://facelessuser.github.io/FuzzyFileNav/installation/

### CODE REVIEW

**Comment by dsernst** [comment]
ah looks like it affects http://facelessuser.github.io/RegReplace/installation/ too

**Comment by facelessuser** [comment]
Yeah, I copied and pasted that page amongst all of my plugins to save time.   Thanks for fixing this here.

**Comment by dsernst** [comment]
:smile:

**Comment by facelessuser** [comment]
Couple more fixes pushed.  Docs have been regenerated.

**Comment by dsernst** [comment]
:+1:

**Pull request merged**
